version: '3'

services:
  app:
    image: node:18.3
    user: 'node'
    platform: linux/amd64
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - 3000
    ports:
      - '3000:3000'
    command: npm run start:dev
