POST {{host}}/appointments
Content-Type: application/json

{
  "staff_member_id": 1,
  "client_id": 1,
  "start_at": 1656339201,
  "end_at": 1656339300,
  "name": "1st appointment"
}

###
GET {{host}}/appointments

###
GET {{host}}/appointments/338ed98e-93bc-469d-b709-18b51ddcf62a